export const scaleFactor = 4;

export const dialogueData = {
    pc: `Este es mi PC super potente, donde escribo código para crear cosas chulísimas. Una imagen vale más que mil palabras, así que es mejor si directamente ves mis proyectos en <a href="https://github.com/minerikart" target="_blank">GitHub</a>.`,
    "cs-degree": `Sobre mí: me llamo Erika, soy Desarrolladora de Software y estudié un CFGS en Desarrollo de Aplicaciones Multiplataforma. Me apasiona Linux y el Software Libre, y siento especial interés por el lenguaje de programación C# y el desarrollo de videojuegos en Unity.`,
    "sofa-table": `Este es mi sofá confortable, donde paso mis ratos de ocio leyendo un buen libro, viendo la TV o jugando a la videoconsola. Por cierto, desde hace un tiempo vengo jugando a la saga <a href="https://es.wikipedia.org/wiki/Persona_(serie)" target="_blank">Persona</a> y se ha convertido en una de mis favoritas. La recomiendo totalmente.`,
    tv: `De vez en cuando me gusta hacer una maratón de series en Netflix. Algunas de las últimas que he visto son <a href="https://www.netflix.com/es/title/81435684" target="_blank">Arcane</a>, <a href="https://www.netflix.com/es/title/81517188" target="_blank">Alquimia de Almas</a>, <a href="https://www.netflix.com/es/title/81054853" target="_blank">Cyberpunk: Edgerunners</a> y <a href="https://www.netflix.com/es/title/81564899" target="_blank">Dungeon Meshi</a>. ¿Conoces alguna?`,
    bed: `Esta es mi camita. La mayor parte del tiempo la ocupa mi perra <i>Kira</i> (su nombre significa "alegría"), pero es generosa y la comparte conmigo por las noches. Kira es una perrita bodeguera muy cariñosa, ¡y la quiero un montón!`,
    resume: `Puedes ver mi currículum digital en <a href="https://www.linkedin.com/in/minerikart" target="_blank">LinkedIn</a>. Siempre estoy abierta a nuevas oportunidades, ¡así que no dudes en conectar conmigo!`,
    projects: `Este portfolio se hizo usando <a href="https://kaboomjs.com" target="_blank">Kaboom.js</a>, una librería para hacer juegos en JavaScript. Puedes encontrar todos mis proyectos de videojuegos en mi perfil de <a href="https://minerikart.itch.io" target="_blank">Itch.io</a>.`,
    library: `Tengo mogollón de libros en la estantería. Me encanta leer, sobre todo novelas extranjeras, como <a href="https://es.wikipedia.org/wiki/Solo_Leveling" target="_blank">Solo Leveling</a>, <a href="https://es.wikipedia.org/wiki/Overlord_(novela_ligera)" target="_blank">Overlord</a>, <a href="https://es.wikipedia.org/wiki/Omniscient_Reader%27s_Viewpoint" target="_blank">Omniscient Reader's Viewpoint</a> y muchas más. Ah, sí, y a menudo también leo libros sobre ingeniería del software, como <a href="https://es.wikipedia.org/wiki/El_programador_pragm%C3%A1tico" target="_blank">El Programador Pragmático</a>.`,
    exit: `El mundo exterior es tan aburrido... Mejor me quedo en casa.`,
};
